// 
// THIS FILE HAS BEEN GENERATED AUTOMATICALLY
// DO NOT CHANGE IT MANUALLY UNLESS YOU KNOW WHAT YOU'RE DOING
// 
// GENERATED USING @colyseus/schema 2.0.36
// 

import { Schema, type } from '@colyseus/schema';

/**
 * Represents the physics state of a vehicle in the game.
 * Contains position, rotation, and velocity data for physics simulation.
 * This class is automatically generated by @colyseus/schema.
 */
export class PhysicsState extends Schema {
    /** X-coordinate of the vehicle's position */
    @type("number") public positionX: number = 0;
    /** Y-coordinate of the vehicle's position */
    @type("number") public positionY: number = 0;
    /** Z-coordinate of the vehicle's position */
    @type("number") public positionZ: number = 0;
    /** X-component of the vehicle's rotation quaternion */
    @type("number") public quaternionX: number = 0;
    /** Y-component of the vehicle's rotation quaternion */
    @type("number") public quaternionY: number = 0;
    /** Z-component of the vehicle's rotation quaternion */
    @type("number") public quaternionZ: number = 0;
    /** W-component of the vehicle's rotation quaternion */
    @type("number") public quaternionW: number = 1;
    /** X-component of the vehicle's linear velocity */
    @type("number") public linearVelocityX: number = 0;
    /** Y-component of the vehicle's linear velocity */
    @type("number") public linearVelocityY: number = 0;
    /** Z-component of the vehicle's linear velocity */
    @type("number") public linearVelocityZ: number = 0;
    /** X-component of the vehicle's angular velocity */
    @type("number") public angularVelocityX: number = 0;
    /** Y-component of the vehicle's angular velocity */
    @type("number") public angularVelocityY: number = 0;
    /** Z-component of the vehicle's angular velocity */
    @type("number") public angularVelocityZ: number = 0;
    /** Current tick */
    @type("number") public tick: number = 0;
    /** Timestamp of the state in milliseconds */
    @type("number") public timestamp: number = 0;
    /** Last processed input tick */
    @type("number") public lastProcessedInputTick: number = 0;
}
